# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc4c5b0974f1dfb322bf39cd131aa889103dfcec5e1e6c42a827daf27246f3f928e679ca1785090ae3aca7b8e23d483bc98c02f95457567007aea5a64a505100

test:
  secret_key_base: 0bfec4c8a99059f628abde69eb45fa2da2fd53d343ec89391ffaaa502053c84db9468082e8ff82e947727e8c2f3dbdb13c1244ff9cfc2c8563891cacba120e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
